services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: minihrm-dynamodb
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    working_dir: /home/dynamodblocal

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: minihrm-dynamodb-admin
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=ap-southeast-1
    depends_on:
      - dynamodb-local

  cognito-local:
    image: jagregory/cognito-local:latest
    container_name: minihrm-cognito
    restart: unless-stopped
    ports:
      - "9229:9229"
    environment:
      - PORT=9229
    volumes:
      - ./.cognito:/app/.cognito
